name: Generate Documentation

on:
  push: {}
  workflow_dispatch:

env:
  DIR: "."
  FILE: "docs"

jobs:
  build:
    name: build-docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Typst
        uses: typst-community/setup-typst@v3
        id: setup-typst

      - run: typst compile docs.typ

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE }}.pdf
          path: $%{{ env.DIR }}

  deploy:
    needs: build
    name: deploy-docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.FILE }}.pdf

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.DIR }}
          force_orphan: true
